### ISSUE TITLE
[hw2-manual coverage] number of testcases

### ISSUE THREAD

**Issue by spearo2** [swtv-kaist/cs458-spring23#11]
I have a question regarding homework 2.
I might have misunderstood the instruction in last Tuesday's class, but as far as I remember the number of test cases must be exactly 10 while the pdf instruction says "at least 10". 

Would it be okay if the number of test cases exceed 10?

**Comment by swtv-kaist** [comment]
Yes, you should make at least 10 test inputs as written in the hw
description.


2023년 3월 27일 (월) 오후 10:34, Zack Lee ***@***.***>님이 작성:

**Comment by spearo2** [comment]
Thank you so much!
