### ISSUE TITLE
[HW02] Format of test script and text files

### ISSUE THREAD

**Issue by jaehyun1ee** [swtv-kaist/cs458-spring23#12]
Hi, I have some questions regarding the format of the test script and text files to submit.

**1. Format of `test_script`**

For `test_script`, can we safely assume that the binary `grep20` in the testing environment can be executed like,

```shell
$ grep20 "foo" bar.txt
```

as written in the Homework description, or should we write the commands like

```shell
$ ./grep20 "foo" bar.txt
```

**2. Format of text files**

Can I submit a directory containing the text files to be used in my commands?

To be more specific, I would like to submit a directory organized as follows,
```plaintext
dir0
| - subdir0
  | - 0.txt, 1.txt, 2.txt, ...
| - subdir1
  | - a.txt, b.txt, 3.txt, ...
```

such that I can use the following command.
```shell
$ grep20 "foo" dir0/subdir0/0.txt
```

Am I allowed to submit such a directory containing text files?

Sorry for the late question, and thank you in advance :)

**Comment by swtv-kaist** [comment]
A1. You can write ```./grep20 "foo" bar.txt``` in your test script.

B2.  
> Am I allowed to submit such a directory containing text files?

Yes.  As long as your test script runs correctly, directory structure does not matter.  TAs will execute your test script.

**Comment by jaehyun1ee** [comment]
Thank you for the clarifications, professor!
