### ISSUE TITLE
[HW-kcov] question about example-kcov.c

### ISSUE THREAD

**Issue by overflow218** [swtv-kaist/cs458-spring23#14]
Dear TA
I have some questions about example about example-kcov.c.

1. what is the rule for output print format? 
for example, there are 17 print of branches in example, but total branch number is 30. 
- where is missing 13 branches? (ex. ELSE branch is missing)
- should I determine the unique number for ID field? 
- should print format sort by line number?

2. how can example-kcov.c have 30 branches? 
if mine and example have different rule for count branch, then is it okay to have different number of branch?
Thank you!

-----
조교님 안녕하세요 과제 진행중 궁금한점이 있어 질문드립니다. 
1. 결과 출력형식에 대해 질문이 있습니다. 예시를 보면 else절 같은건 출력에 안나와있는데 전체 카운트에는 포함되는 것 같습니다. 
어떤 것은 출력하고 어떤 것은 안하는지 출력형식에 대한 명확한 기준이 있을까요? 그리고 ID 필드의 값은 제가 임의로 할당해주는 건가요?
마지막으로 출력 형식은 라인넘버에 맞게 정렬되어야하는 걸까요? 작성하다보니 코드상의 순서와 AST로 변환시 내부노드안에 들어가는 순서가 달라지는 것 같아서 처리가 필요할지 질문드립니다.
2. example-kcov.c를 분석한 결과 예시에는 브랜치가 30개가 있다고 나옵니다. 제가 작성한 결과와는 차이가 있는데 브랜치를 
판정하는 기준이 달라지면 달라질 수 있을 것 같습니다. 달라도 문제 없는 건가요? 아니면 무조건 30개를 맞추도록 기준을 정해야하는지 질문드립니다.
감사합니다.

**Comment by swtv-kaist** [comment]
A1.  
> where is missing 13 branches? (ex. ELSE branch is missing)

You are right.  The HW description was not precise. The output of  ```./kcov-branch-identify example-kcov.c``` in the HW description shows conditional statements (not branches).  I revised the HW description and uploaded the correct HW description to KLMS. 

As you know, 1 ```if``` statement has 2 branches and 1 ```case``` statement corresponds to 1 branch. Thus, 17 conditional statements in the example have 30 branches.

A2. 
> should I determine the unique number for ID field?

Yes, ID field should be unique.

A3. 
> should print format sort by line number?

Yes, the output should be sorted by line #.

**Comment by overflow218** [comment]
Thank you!
