### ISSUE TITLE
[hw2-Kcov] convert *.i file to *.c file

### ISSUE THREAD

**Issue by overflow218** [swtv-kaist/cs458-spring23#17]
Dear TA,
as I understood, to solve prob 4 
1. get input *.i file and insert needed code
2. convert *.file to new *.c file
3. compile and execute new *.c file 

I'm managed to change given source code, insert probe, and make a new file. 
but I'm stuck at converting input *.i file to new *.c file. 
I googles it, but couldn't find a good answer. 
I think I'm missing something. 
what should I study to solve this problem? 
Thank you! 

----- 
조교님 안녕하세요 
입력으로 들어온 파일을 수정해서 필요한 코드를 심고, 새로운 파일로 만드는것까지는 그럭저럭 해냈습니다. 
그런데 *.i 파일을 *.c 파일로 변환하는게 문제의 조건이라고 이해했는데 이 부분에서 조금 어려움을 겪고 있습니다. 
혹시 제가 이부분에서 뭔가 놓치고 있거나 공부해야할 부분이 있다면 알려주시면 감사하겠습니다. 
감사합니다.

**Comment by swtv-kaist** [comment]
> I'm stuck at converting input *.i file to new *.c file.

No, you do not have to convert your instrumentd *.i file to *.c file.  Just compile and execute your instrumented *.i file to measure branch coverage is ok.

**Comment by overflow218** [comment]
Thank you professor!
