### ISSUE TITLE
[HW3 - Kcov] about neccesary header file

### ISSUE THREAD

**Issue by overflow218** [swtv-kaist/cs458-spring23#18]
Dear TA,
I need some functions in "string.h" file to read and write result data to *.dat file.
however, if given *.i file does not include "string.h", then I can't use this functions. 

what can I do in this situation?
should I manually implement function like strlen(), strtok() or something?
as I intentionally include "string.h" file to *.i file and test it, it works well.

Thank you!
---- 
안녕하세요 조교님
결과 파일을 읽고 쓰려면 스트링 관련 함수가 조금 필요한 상황입니다. 
제가 이해한바로는 주어진 *.i 파일에서 #include <string.h> 내용이 없었으면 제가 따로 추가하는건 어려운 걸로 이해했습니다. 
일단 일부러 *.c 파일에 #include <string.h> 를 추가하고 .i 파일을 만들어서 테스트했을땐 잘 작동하는 것 확인했습니다. 
혹시 관련 함수들(strlen(), strtok() 등등)까지 제가 수동으로 구현해서 사용해야하나요?
감사합니다.

**Comment by YoungseokCh** [comment]
> should I manually implement function like strlen(), strtok() or something?

No, you don't need to implement string library functions.

> If given *.i file does not include "string.h", then I can't use this functions.

It is okay to make your code insert `#include <string.h>` at the top of `*.i` file.

**Comment by overflow218** [comment]
Thank you!
