### ISSUE TITLE
[hw3 - kcov] questions about hw3

### ISSUE THREAD

**Issue by overflow218** [swtv-kaist/cs458-spring23#19]
Dear TA, 
sorry for too many questions.. 
I'm almost done implementing, but have some minor issues. 

1. in question 5, grep.i file contins below enum declaration. 
`enum = {_ISupper = ((0) < 8 ? ((1 << (0)) << 8) : ((1 << (0)) >> 8)), ... } ;`
my kcov changed this like below
`_ISupper = ((((0) < 8)?(mycov_onTrueCondition(135,4782),1):(mycov_onFalseCondition(135,4782),0)) ? ((1 << (0)) << 8) : ((1 << (0)) >> 8)),`
I tried build gcc grep.i, but I got an error
`error: enumerator value for ‘_ISupper’ is not an integer constant`
and this is because `function call is not allowed in a constant expressionC/C++(59)`

so I tried to check wheather this ? : is in enum declaration, but I didn't find a good way. 
what should I study for this?

2. I inject a code that save result to *.dat file at the end of target source code's main file.
I find this location by check "return" statment's location. 
but in the case of grep.c, I does not have a return statement, but calls 'exit' function. 
can you give me some help about this?

Thank you
---- 
조교님 안녕하세요 
우선 너무 자주 질문을 올려 죄송합니다 ㅠㅠ 
example-kcov.i 에 대해서는 잘 작동하여 이를 grep.i 파일에 대해서도 적용해보는 중입니다. 
제가 작성한 kcov 로 변환은 잘 되는데 몇가지 문제가 있습니다. 
1. enum 열거형 내부에서 ? : 삼항 연산자를 사용한 경우가 있는데 이게 branch 개수에는 포함이 되는데 저걸 위의 코드와 같이 변환하게되면 선언안에 함수가 들어갈 수 없다고 에러가 나옵니다. 그래서 enum 안에 있는건지 맥락을 좀 확인해보려했는데 좋은 방법을 찾지 못했습니다. 혹시 뭘 공부하거나 찾아보면 될까요?
2. 타겟 소스코드의 메인문 마지막에 데이터를 다시 *.dat 파일에 적어주는 부분 코드를 심었습니다. 이 위치를 판단하는 기준으로 리턴문의 위치를 생각했는데 grep.c 의 경우 메인 함수가 return 문 없이 exit() 호출만 하고 종료되어 버려서 저장하는 코드가 호출되지 않는 상황입니다. 
역시 이런 부분을 핸들링하려면 어디를 좀 더 찾아봐야할까요? 
감사합니다

**Comment by swtv-kaist** [comment]
A1.  Please carefully read and address the gcc error message to remove the error.  You may look at stackoverflow to find similar issues and explanations.  TAs may not help your debugging.

A2.  You may also insert a probe at exit() (and/or related functions) call site.

**Comment by overflow218** [comment]
thank you!
