### ISSUE TITLE
[HW03] Expected behavior of kcov and the submission template

### ISSUE THREAD

**Issue by jaehyun1ee** [swtv-kaist/cs458-spring23#20]
Hello, here are some questions on the expected behavior of `kcov` and the submission template.

## Behavior of `kcov`

**1. For the following switch statement, how should `kcov` measure its coverage?**

```C
int a = 100;
switch (a) {
  case 100:
    a += 1;
  case 200:
    a += 2;
}
```

Since there is no `break;` in `case 100`, the code reaches `case 200`. Then can we consider that `a = 100` covers the branch `case 200` also?

**2. What if multiple binaries happen to share `coverage.dat`?**

Suppose that we have two (independent) source files `a.i` and `b.i`. They are instrumented and compiled to `a-cov` and `b-cov`, respectively (they are in the same directory).

The first command `./a-cov` generates `coverage.dat`. Now, if we type command `./b-cov`, what is the expected behavior?

- Should it check that `coverage.dat` belongs to `a-cov` and overwrite the contents?
- If so, what should be the criteria for validating `coverage.dat`? The format of `coverage.dat` doesn't hold the file name that it came from.

## Submission Template

**3. In `kcov-branch-identify`, can we implement outside `VisitStmt` and `VisitFunctionDecl`?**

The given template file says `// Fill out this function for your homework` in those two functions.

But can I implement some functions in `MyASTConsumer` and define some class fields in `MyASTVisitor`?

---

Thank you in advance!

**Comment by swtv-kaist** [comment]
1.
> can we consider that a = 100 covers the branch case 200 also?

Yes.

2.
> The first command ./a-cov generates coverage.dat. Now, if we type command ./b-cov, what is the expected behavior?

For your convenience, you can assume that only ONE executable file (i.e., grep20) generates ```coverage.dat```. 

3.
> But can I implement some functions in MyASTConsumer and define some class fields in MyASTVisitor?

Yes, you can do that if you have a good reason to do it.

**Comment by jaehyun1ee** [comment]
Thank you for the answer, professor :)
