### ISSUE TITLE
How to count clauses and predicates in condition?

### ISSUE THREAD

**Issue by duncan020313** [swtv-kaist/cs458-spring23#23]
In lecture note 10, there are examples
```
if ((a&&b)||c){
  s1;
}
else {
  s2;
}
```
transforms into
```
d = a&&b;
e = d||c;
if (e) {
  s1;
}
else {
  s2;
}
```

Considering the way we deal with clause and predicate before,
I think we should look at the predicate "e" as "e" itself rather than "d||c".

But the lecture note said transformed code has 2 clauses d and c.
So, it said to satisfy CACC, transformed code requires 3 tests.
However, if we consider "e" as "e" itself, we need 2 tests.

Am I thinking something wrong?

**Comment by swtv-kaist** [comment]
I agree that the lecture 10 slides are confusing.  I revised and uploaded the new lecture 10 slides that change the transformed code (2) as follows:
```
d = a && b;
if (d||c) {
  s1;
}
else {
  s2;
}
```

**Comment by duncan020313** [comment]
Thank you!!
