### ISSUE TITLE
[Coverage] ICC on a single-clause predicate

### ISSUE THREAD

**Issue by jaehyun1ee** [swtv-kaist/cs458-spring23#24]
Hello, I have one question on logic coverage criteria.

**If a predicate `P` has a single clause, say `A`, can we define its `ICC`?**

`A` is the one and only major clause and there is no minor clause, so `RICC` and `GICC` would have the same meaning here.

The definition of `ICC` requires four cases:
- `A` is true when `P` is true
- `A` is false when `P` is true
- `A` is true when `P` is false
- `A` is false when `P` is false

But it is nonsense that `A` is false when `P` is true, and `A` is true when `P` is false. So I think for a predicate `P = A`, `ICC` is infeasible and its TR is an empty set.

How can we handle such case, to ensure that variants of `ICC` subsumes `PC` in the coverage subsumption hierarchy?

**Comment by swtv-kaist** [comment]
> How can we handle such case, to ensure that variants of ICC subsumes PC in the coverage subsumption hierarchy?

In this case, the subsumption relation between ICC and PC is _vacuously true_ since no test input satisfies ICC ;-)
(see what "vacuously true" means: https://en.wikipedia.org/wiki/Vacuous_truth )

**Comment by swtv-kaist** [comment]
But, in this case, the subsumption relation between CoC and ICC may not be true, which confuses me...

**Comment by jaehyun1ee** [comment]
Actually, I found a helpful mention about this issue in the textbook.

> The simplest solution is to simply ignore infeasible requirements, which usually does not affect the quality of the tests.
However, a better solution for some infeasible test requirements is to consider the counterparts of the requirements in a subsumed coverage criterion. (page 113)

Since `ICC` is infeasible, we may consider it as the subsumed coverage criterion `PC`. Then `CoC` will safely subsume `ICC` in turn.

Would this kind of interpretation work?

**Comment by duncan020313** [comment]
I think the coverage hierarchy is derived from each coverage criterion.

Thus, we don't need to consider whether test requirements are feasible or not.

Then, in this case, ICC still subsumes PC.

**Comment by swtv-kaist** [comment]
The subsumption relations among test criteria may not be clean if we consider infeasible requirements seriously. 
Thus, as @jaehyun1ee pointed out, the textbook mentions about the hierarchy among logic coverage criteria as follows:  

> The diagram assumes that infeasible test requirements are treated on a best effort basis, as explained above. Where such an approach does not result in feasible test requirements, the diagram assumes that the infeasible test requirements are ignored.

**Comment by jaehyun1ee** [comment]
Thank you for the kind answers :) Infeasibility seems to be a very subtle topic...!
