### ISSUE TITLE
[Coverage] About GICC in Logic Coverage Example

### ISSUE THREAD

**Issue by hy38** [swtv-kaist/cs458-spring23#25]
Hello, I have a question about the Example in the Logic Coverage slide, specifically about GICC.

![image](https://user-images.githubusercontent.com/34434143/232231963-e7c9705d-51ab-4cfc-a4e4-6b5b6f5ef0f3.png)

From this example, to my best understanding, GICC for major clause b should be {5, 6} x {7, 8} for p=F, and **{(1, 3), (1, 4)} for p=T**.
It is because for p=T (and F), b should be covered with T and F while minor clause a and c doesn't have to be the same for each b (i.e., b=T and b=F).

Similarly, for major clause c, GICC should be {5,7} x {6, 8} for p=F, and **{(1, 4), (3, 4)} for p=T**.

However, the answer in the slide doesn't include (1,4) for p=T.

Am I missing something?

Thank you :)

**Comment by swtv-kaist** [comment]
> GICC for major clause b should ... {(1, 3), (1, 4)} for p=T.

No.  (1, 4) cannot make b a major clause, since tc4 satisfies *p_b* (i.e., tc4 sets a and c to cause b to determine a/\ (!b \\/ c) ).  
For ICC, a major clause should NOT determine its predicate.

![image](https://user-images.githubusercontent.com/29851315/232234737-09d6408f-256a-4835-bb93-7d3cd6e71846.png)

**Comment by hy38** [comment]
Thank you so much for answering :)

To clarify, because ICC do **not** determine its p,

for major clause b, when finding sets of test cases for GICC (and RICC), _p_b_ should be **false** since _p_b_=true indicates that b determines p? 

And, similarly, because ACC **do** determine its p,

for major clause (let's just say) b, when finding sets of test cases for CACC (and RACC), 

_p_b_ should be **true** since _p_b_=true indicates that b determines p? 

Did I understand it in a right way?

**Comment by swtv-kaist** [comment]
> for major clause b, when finding sets of test cases for GICC (and RICC), p_b should be false since p_b=true indicates that b determines p?

Yes.

> for major clause (let's just say) b, when finding sets of test cases for CACC (and RACC),
p_b should be true since p_b=true indicates that b determines p?

Yes.

**Comment by hy38** [comment]
Thank you so much for replying even at this late hour :)
