### ISSUE TITLE
[HW05] Measuring branch coverage for LLVM switch instruction

### ISSUE THREAD

**Issue by jaehyun1ee** [swtv-kaist/cs458-spring23#27]
Hi, I have three questions regarding the measurement of branch coverage of `switch` in LLVM IR.

**1. As we did in `kcov`, when counting the total number of branches, does each branch (or case) of `switch` count as 1 branch, not 2?**

**2. In relation to the first question, do we consider that visits to each case of `switch` counts as taking the true branch?**

**3. How should we measure the branch coverage of a `switch` statement without `break`s between the cases?**

Consider a `switch` statement in a C program,

```C
int main() {
  char a = 'a';
  int y = 0;
  switch (a) {
    case 'a':
      y = 1;
    case 'b':
      y = 2;
    case 'c':
      y = 3;
    default:
      y = 4;
  }
}
```

In `kcov`, since `a` is `'a'`, we have considered it as taking all of the `case 'a'`, `case 'b'`, `case 'c'`, and `default` branches.

But when the program is translated into a `switch` instruction in LLVM IR,

```LLVM IR
; Function Attrs: noinline nounwind optnone uwtable
define dso_local i32 @main() #0 {
entry:
  %retval = alloca i32, align 4
  %a = alloca i8, align 1
  %y = alloca i32, align 4
  store i32 0, i32* %retval, align 4
  store i8 97, i8* %a, align 1
  store i32 0, i32* %y, align 4
  %0 = load i8, i8* %a, align 1
  %conv = sext i8 %0 to i32
  switch i32 %conv, label %sw.default [
    i32 97, label %sw.bb
    i32 98, label %sw.bb1
    i32 99, label %sw.bb2
  ]

sw.bb:                                            ; preds = %entry
  store i32 1, i32* %y, align 4
  br label %sw.bb1

sw.bb1:                                           ; preds = %entry, %sw.bb
  store i32 2, i32* %y, align 4
  br label %sw.bb2

sw.bb2:                                           ; preds = %entry, %sw.bb1
  store i32 3, i32* %y, align 4
  br label %sw.default

sw.default:                                       ; preds = %entry, %sw.bb2
  store i32 4, i32* %y, align 4
  br label %sw.epilog

sw.epilog:                                        ; preds = %sw.default
  %1 = load i32, i32* %retval, align 4
  ret i32 %1
}
```

Here, `%conv` evaluates to `97`, so we first `switch` from `entry` to `sw.bb`, then `br` unconditionally from `sw.bb` to `sw.bb1`, `sw.bb1` to `sw.bb2`, and `sw.bb2` to `sw.default`.

In our `ccov` assignment, we are supposed to measure the branch coverage for conditional `br`s and `switch`.

So in this case, can we consider that the program only takes the `entry` to `sw.bb` branch, and do not increment the counts for the subsequent `sw.bb1`, `sw.bb2`, `sw.default` that are visited via unconditional `br`s from `sw.bb`?

**Comment by YoungseokCh** [comment]
Thank you for the question. Indeed, we just updated the description for coverage measurement of switch instructions (Announced in KLMS), so please check it.

> 1. As we did in kcov, when counting the total number of branches, does each branch (or case) of switch count as 1 branch, not 2?

Each case (or default) condition is counted as one branch.

> 2. In relation to the first question, do we consider that visits to each case of switch counts as taking the true branch?

Yes. Visits to each case of switch are regarded as taking the true branch.

> 3. How should we measure the branch coverage of a switch statement without breaks between the cases?

We are measuring the coverage in LLVM IR level, not C. Since there is no `break` in LLVM IR, you don't need to think of it. 

> So in this case, can we consider that the program only takes the entry to sw.bb branch, and do not increment the counts for the subsequent sw.bb1, sw.bb2, sw.default that are visited via unconditional brs from sw.bb?

You are right. Just consider it as taking only `entry -> sw.bb` branch.

**Comment by jaehyun1ee** [comment]
Thank you for the clarifications & the updates :)
