### ISSUE TITLE
[HW05] Measuring Total branches

### ISSUE THREAD

**Issue by hy38** [swtv-kaist/cs458-spring23#28]
Hello,

I have a brief question for hw05.

When counting the total branches, the file "hw-kcov-llvm-v5.pdf" introduces me to double the branch conditions in a target program.

As far I understand, for the code given (i.e., example.c), I guess the total branch should be 16 rather than 18.

It is because we can say that a switch instruction has one branch condition without considering how many case statements there are. 

The example code seems to have 6 br instructions, 2 switch instructions. And each instruction has one branch condition.

This leads me (6 + 2) * 2 = 16 total branches.

Am I thinking something wrong?
Quite confused..

<img width="419" alt="image" src="https://github.com/swtv-kaist/cs458-spring23/assets/34434143/58ca9309-7e1f-4a38-8cb5-8648794bba66">

Thank you :)

**Comment by hy38** [comment]
I think when we count each cases and defaults as one branch condition, it can make sense.
And there seems to be no reason not to count cases and defaults as a branch condition.

2 * 6 + 3 + 3 = 18

I guess I made a silly question.
Sorry for the confusion.

**Comment by YoungseokCh** [comment]
In documentation, 'Two times number of total branch' made this confusion and it is not true in general. You can ignore that part. Thanks!
