### ISSUE TITLE
[HW06] What to Grep from Input Seed

### ISSUE THREAD

**Issue by hy38** [swtv-kaist/cs458-spring23#29]
Hello,

I have a simple question about fuzzing grep.

I've been provided the empty seed named "init_input_empty".

However, I'm not sure what to grep from this seed.

For example, if I want to grep "apple" in a text file named "fruits.txt", I may grep ./grep apple ./fruits.txt

In our homework 5, we would need to have "something" to grep from the input file as ./grep something ./init_input_empty

What do we want to grep? **Is it specified? Or is it anything I want?**

**Comment by hy38** [comment]
Also, I want to clarify if we should make the init_input_empty be the first cmdline argument or the second.

I think there are 2 options:

(1) ./grep something ./init_input_empty

(2) ./grep ./init_input_empty something

For question 1,

Can I assume that the **first option** is what you expect us to do and the file init_input_empty is what afl should mutate?

Sorry for the minor questions. Just wanted to make it clear.

**Comment by swtv-kaist** [comment]
1.
> In our homework 5, we would need to have "something" to grep from the input file as ./grep something ./init_input_empty

You may not be familiar w/ how to use ```afl-fuzz``` command. Let me give you a hint about how to apply afl++ to grep20 (see the slide 5 in the AFL++ lecture). For example,

```afl-fuzz -i ./input_seeds -o ./out -- ./grep20 "[[:digit:]]\{2\}[ -]\?[[:digit:]]\{10\}" @@```

where you should store the ```init_input_empty``` file in ```./input_seeds```.  

Note that, in afl++ command-line arguments. you should specify a *directory* that contains initial seed file(s), not initial seed input files themselves.

![image](https://github.com/swtv-kaist/cs458-spring23/assets/29851315/0eadb862-31ac-433d-b059-fc7251587a09)

2
> What do we want to grep? ... is it anything I want?

Yes, you can give any command line arguments to grep20 as you like.

**Comment by hy38** [comment]
Thank you for the kind reply!

I greatly appreciate it :)
