### ISSUE TITLE
[HW06] grep command line options

### ISSUE THREAD

**Issue by jaehyun1ee** [swtv-kaist/cs458-spring23#30]
In HW02, I used the `-f [file]` option in `grep` to obtain high coverage, which allows to use patterns written in the `[file]`.

May I use `-f` option in Problem 1, 2, and 3?
Specifically, I would like to include some file named `pattern.txt` and fuzz with `afl-fuzz ... -- grep -f pattern.txt @@`.

If it is okay, should I submit the `pattern.txt` that I have used also?

**Comment by swtv-kaist** [comment]
> May I use -f option in Problem 1, 2, and 3?

Yes, you can use any command line options to grep20 as you like.  
But, you should check if your command line options are correctly applied to grep20 under afl++ environment.

> If it is okay, should I submit the pattern.txt that I have used also?

Yes.  You should submit all relevant files to reproduce your fuzzing results.

**Comment by jaehyun1ee** [comment]
Thank you for the clarifications, professor :)
