### ISSUE TITLE
[HW06] Branch coverage: AFL++ vs gcov

### ISSUE THREAD

**Issue by hy38** [swtv-kaist/cs458-spring23#31]
Hello,

While doing homework #6, I've captured that the gap of branch coverage reported by AFL++ vs gcov is somehow large than expected.

Specifically, AFL++ gave 16.83% as the total branch coverage while gcov only gave 5.36%.

Is this amount of gap a normal phenomenon?

**Comment by YoungseokCh** [comment]
Usually, the AFL++ coverage is not that different from gcov coverage. Did you run all the `+cov` cases produced by AFL++ to measure the gcov coverage?

**Comment by YoungseokCh** [comment]
I am closing this since this stream is not active. You can reopen this if you have any related questions.
