### ISSUE TITLE
[HW06] Disk Space Issue

### ISSUE THREAD

**Issue by hy38** [swtv-kaist/cs458-spring23#34]
Hello,

While fuzzing grep, I've got an error as below:

<img width="997" alt="image" src="https://github.com/swtv-kaist/cs458-spring23/assets/34434143/600c69f0-5ac7-4e3f-bae2-d75d256cb0af">

I guess this is a disk space issue.

Could you check if there is sufficient memory left in the server?

FYI: My allocated server is verifier18 :)

Thank you!

**Comment by YoungseokCh** [comment]
The number of inodes in the disk reached its capacity for that moment. I just cleaned up the disk space to resolve it.
Sorry for the inconvenience.

**Comment by hy38** [comment]
@3-24 Hello, 

Thank you for making disk spaces available.

However, I guess AFL needs additional settings after the server reboot.

<img width="876" alt="image" src="https://github.com/swtv-kaist/cs458-spring23/assets/34434143/adbf059f-d338-468e-8adb-4fda0b10828e">

I think I can't figure this out on my own without permission.

Could you give me some help?

**Comment by YoungseokCh** [comment]
I forgot to apply the settings, applied it just now. Could you check it again?

**Comment by hy38** [comment]
Works well! 

Thank you :)
