### ISSUE TITLE
[HW07] Using gcov on the replay binary

### ISSUE THREAD

**Issue by jaehyun1ee** [swtv-kaist/cs458-spring23#35]
Hi, I have one question about using the `_replay` binary for measuring branch coverage with `gcov`.

When `tcas-mod-crown_replay` is run with `crown_replay`, and its coverage information is retrieved by `gcov`,

it seems like the conditions used in `SYM_assume` are considered as branches also.

For example, `SYM_assume(a >= 1 && a <= 5)` is regarded as 4 branches in `gcov`.

So for the `main` function where the instrumentation for `CROWN` is inserted, the reported branch coverage doesn't seem so accurate.

**Is there a way to exclude the `CROWN` instrumentations from the coverage measurement in `gcov`? 
Or, is it okay to report the coverage as it is (including the `SYM_assume` instrumentations)?**

**Comment by swtv-kaist** [comment]
1.
> Is there a way to exclude the CROWN instrumentations from the coverage measurement in gcov?

Yes. To ignore ```SYM_assume``` in ```<target>_replay```, you should add the following directives in your concolic testing driver: 
```
#ifndef CROWN_REPLAY
  SYM_assume(a >=1 && a <= 5);
#endif
``` 

Note that ```crownc``` builds ```<target>_replay```  binary file  with ```-DCROWN_REPLAY``` flag.

2.
I have revised and uploaded the lecture slides that explains how to exclude  ```SYM_assume``` in ```<target>_replay```

**Comment by jaehyun1ee** [comment]
Thank you for the help, professor :)
