### ISSUE TITLE
[HW07] Constraints for the 12 arguments

### ISSUE THREAD

**Issue by hy38** [swtv-kaist/cs458-spring23#36]
Hello,

I'm wondering if I can assume the 12 arguments to be non-negative values.

It is because if I do not, CROWN generates some inputs as "Own_Tracked_Alt = -2147483647", which seems to me **invalid**.

Thank you!

**Comment by swtv-kaist** [comment]
>  I can assume the 12 arguments to be non-negative values.

Not exactly.  3 true/false variables can be 0 (i.e., false).  Also, Alt_Layer_value and Other_RAC can be 0.  
You can assume that the other 7 variables should be positive integers.

**Comment by hy38** [comment]
Thank you for the clarification :)
