### ISSUE TITLE
[HW7] CROWN with argument

### ISSUE THREAD

**Issue by TonyWild** [swtv-kaist/cs458-spring23#37]
In the homework, since tcas-mod receives arguments as input, I modified it like a triangle program we saw in the lecture. Is that okay? Or is there a way to give input as an argument using CROWN? Thank you

**Comment by swtv-kaist** [comment]
>  I modified it like a triangle program we saw in the lecture. Is that okay?

Yes, you can declare the 12 input variables of TCAS as symbolic variables by using ```SYM_int()```
