### ISSUE TITLE
Why does DFS search strategy take such a long time?

### ISSUE THREAD

**Issue by hy38** [swtv-kaist/cs458-spring23#38]
Hello,

I have a question when concolic testing grep with various search strategies.

<img width="998" alt="image" src="https://github.com/swtv-kaist/cs458-spring23/assets/34434143/fca7eb42-74e9-4a4a-8fa4-fe03adb4cc25">

As in the above lecture slide, the DFS strategy takes a very long time iterating 10000 times.

As far as I remember, it was due to some loop related reason, but I can't remember it in detail :(

Could you explain the reason why DFS took such a long time when running CROWN with grep?

Also, I think DFS is the best strategy for finding bugs as in the case of grep.

However, to reach a high coverage in a limited time budget, DFS looks like a bad choice.

So, my question is, is DFS the best strategy when the time budget is unlimited?

Then, what is the best strategy when the time budget is limited?

Thank you :)

**Comment by swtv-kaist** [comment]
> Could you explain the reason why DFS took such a long time when running CROWN with grep?

You can find a reason from the following loop example:
![image](https://github.com/swtv-kaist/cs458-spring23/assets/29851315/233a9ca5-ffdf-4769-8308-03d5c353078d)

If a loop bound is given as a symbolic variable, the loop bound can continuously increase, which will generate longer and longer symbolic path formulas.

> is DFS the best strategy when the time budget is unlimited?
Yes

> what is the best strategy when the time budget is limited?
Well, there exists no single best search strategy in limited time budget.
Instead, you can use all strategies in parallel to improve test effectiveness.

**Comment by hy38** [comment]
Thank you, as always :)
