### ISSUE TITLE
[Coverage] Clarifications on the definitions of TRs for EC and EPC

### ISSUE THREAD

**Issue by jaehyun1ee** [swtv-kaist/cs458-spring23#4]
Hi, I have some questions regarding the definitions of EC and EPC in our lecture slides.

- Definition of EC
 
We have revised the definition of EPC as, ```TR contains each reachable path of LENGTH UP TO 2, INCLUSIVE, in G``` to handle some corner cases. 
 
**Then, shouldn't we also revise the definition of EC to, ```TR contains each reachable path of LENGTH UP TO 1, INCLUSIVE, in G.```?** 

A counterexample would be a graph with only one node, where EC cannot subsume NC without the condition, "LENGTH UP TO 1, INCLUSIVE".

- Definition of TR

In class, we have discussed the TR of EPC for the following graph G as,

<img width="154" alt="image" src="https://user-images.githubusercontent.com/44872014/224946802-31825fd0-0032-41cd-89cd-4609e14ffec4.png">

```
TR_EPC = { (0, 1, 2), (0, 2) }
```

Then all test paths that cover `TR_EPC` will also achieve NC and EC.
But following the definition of EPC STRICTLY, I think the TR should rather be

```
TR_EPC = { (0), (1), (2), (0, 1), (0, 2), (1, 2), (0, 1, 2) }
```

since this TR indeed contains all reachable path of LENGTH UP TO 2, INCLUSIVE, in G.

So I wonder which `TR_EPC` is correct.

**Comment by jaehyun1ee** [comment]
\* I cannot label this issue by myself. Maybe I do not have adequate permission to do so?

**Comment by swtv-kaist** [comment]
> Then, shouldn't we also revise the definition of EC to, TR contains each reachable path of LENGTH UP TO 1, INCLUSIVE, in G.?

You are right. The TR of EC is defined as "TR contains each reachable path of LENGTH UP TO 1, INCLUSIVE, in G"  in the textbook. I modified and uploaded the lecture slides to the CS458 homepage. 

> So I wonder which TR_EPC is correct.

According to the definition of EPC, the following one is correct:
TR_EPC = { (0), (1), (2), (0, 1), (0, 2), (1, 2), (0, 1, 2) }

**Comment by jaehyun1ee** [comment]
Thank you for the clarification, professor :)
