### ISSUE TITLE
Definition of Def-clear

### ISSUE THREAD

**Issue by TonyWild** [swtv-kaist/cs458-spring23#8]
According to the material, the definition of "Def-clear" is as follows:
`A path from l_i to l_j is def-clear with respect to variable v, if v is not given another value on any of the nodes or edges in the path.`

Can def-clear path can have several use nodes with respect to v?

Thank you!

**Comment by A-Mehdi** [comment]
Yes, the def-clear path can have several use nodes.

**Comment by swtv-kaist** [comment]
> Can def-clear path can have several use nodes with respect to v?

Yes. A def-clear path w.r.t. v should retain v's value during the whole path (multiple uses of v does not matter).

**Comment by TonyWild** [comment]
Thanks for the answer! Appreciate it :)
